// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmd9iBKeRg1zIxHhLTjHLNnvr0CB8-8_4',
    appId: '1:860174849717:web:d2545bc1f9919f253d50fc',
    messagingSenderId: '860174849717',
    projectId: 'loginapp-aede5',
    authDomain: 'loginapp-aede5.firebaseapp.com',
    storageBucket: 'loginapp-aede5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjXONljqXFK6geU3gX3CT2NpqBdl8cw9E',
    appId: '1:860174849717:android:8f568e351b87746b3d50fc',
    messagingSenderId: '860174849717',
    projectId: 'loginapp-aede5',
    storageBucket: 'loginapp-aede5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd2K4kqKXQYo18ph6O7bF3JFkHejj87BI',
    appId: '1:860174849717:ios:4f164d34d89cf5ca3d50fc',
    messagingSenderId: '860174849717',
    projectId: 'loginapp-aede5',
    storageBucket: 'loginapp-aede5.appspot.com',
    iosBundleId: 'com.example.loginApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd2K4kqKXQYo18ph6O7bF3JFkHejj87BI',
    appId: '1:860174849717:ios:d5c79406842da9ff3d50fc',
    messagingSenderId: '860174849717',
    projectId: 'loginapp-aede5',
    storageBucket: 'loginapp-aede5.appspot.com',
    iosBundleId: 'com.example.loginApp.RunnerTests',
  );
}
